const indianNameList = [
  "Yodha",
  "Daku",
  "Bhai",
  "Tiger",
  "Singham",
  "Raavan",
  "Shaktimaan",
  "Mahadev",
  "Naagin",
  "Veer",
  "DesiBoy",
  "SwagWaleBhai",
  "Pahadi",
  "GaramMasala",
  "LassiKing",
  "BulletRider",
  "Rajputana",
  "Khiladi",
  "Nawab",
  "Chatori",
  "GullyBoy",
  "Sanskari",
  "BollywoodFan",
  "MirchiQueen",
  "SitarMaster",
  "DholBeats",
  "MasalaMix",
  "Thakur",
  "BiryaniBhai",
  "KarmaKing",
  "KudiPataka",
  "MastMaula",
  "Hindustani",
  "KachaBadam",
  "BapuDaFan",
  "JattDaSwag",
  "SamosaLover",
  "ChaiPeeneWala",
  "KhaatiPeetiFamily",
  "DesiRider",
  "MumbaiKaDon",
  "Jugaadu",
  "Khatarnak",
  "Bindaas",
  "SundarSanskari",
  "RamBharose",
  "Shera",
  "MaaKaSher",
  "AlooParatha",
  "TandooriNights",
  "LadkiPataneWala",
];

const funMessages = [
  "🔥 Ready to rule the gully!",
  "😎 Swag level 9000!",
  "💥 Full desi power activated!",
  "🍗 Biryani before battle!",
  "🤘 Kahaan hai party tonight?",
  "🛵 Riding into the sunset, desi style!",
  "📿 Just took blessings from Mahadev!",
  "💃 Break dance wali entry!",
  "👊 Daku with a heart!",
  "🚀 Flying high on chai energy!",
  "🎤 Mic drop on arrival!",
  "🐯 Tiger is back baby!",
  "🍔 Burger? No bro... Samosa!",
  "💪 Gym gaya tha, ab naam banane chala hoon!",
  "🚨 Don’t mess, desi don is here!",
  "🎯 Seedha dil pe jaake laga!",
  "🛕 Mandir jaa raha hoon… style mein!",
  "💥 Attitude toh bachpan se hi royal hai!",
  "🍿 Popcorn ready, entry scene baaki hai!",
  "👑 Born to rule, not to explain!",
  "🥁 Entry pe dhol bajega!",
  "📱 Bio mein likhlo: Danger ahead!",
  "🚧 No U-Turn, swag is one-way!",
  "🏏 Life = Chakde Phatte + Swag Shots!",
  "🛡️ Dosti mein hero, dushmani mein villain!",
  "🎮 Khel toh ab shuru hua hai!",
  "💣 Level unlocked: Thoda zyada over smart!",
  "🌶️ Masaledaar swag served hot!",
  "🌪️ Tez hawa mein bhi khade rehte hain hum!",
  "🧨 Dialogue delivery se hi darr lagta hai sabko!",
  "🕺 Desi thumka > any dance step!",
  "📍 Location: Dil + Dimaag dono mein!",
  "🦸‍♂️ Common name, uncommon game!",
  "🎸 Mic check 1 2, swagger's coming through!",
  "⚔️ Bina script ke bhi blockbuster hu main!",
];

export function generateRandomMessage() {
  const name =
    indianNameList[Math.floor(Math.random() * indianNameList.length)];
  const message = funMessages[Math.floor(Math.random() * funMessages.length)];
  const object = { name, message };
  return object;
}
